### ISSUE TITLE
when len % 64 === 0, we can reduce one time of mix

### ISSUE THREAD

**Issue by gzm55** [wangyi-fudan/wyhash#55]
If `len = n * 64` where n >= 2`, we will do a a mix again, that could be saved.

Now:

```c
   if(_likely_(i>=4)) return _wymix(_wyr4(p)^secret[0],_wyr4(p+i-4)^seed);
   else return _wymix((_likely_(i)?_wyr3(p,i):0)^secret[0],seed); // come here if len = 0, 1, 2, 3, 128, 128 + 64....
``` 

Modified:
```c
   if(_likely_(i>=4)) return _wymix(_wyr4(p)^secret[0],_wyr4(p+i-4)^seed);
   else if(_likely_(loop)) return seed; // come here if len = 128, 128 + 64, ...
   else return _wymix((_likely_(i)?_wyr3(p,i):0)^secret[0],seed); // come here if len = 0, 1, 2, 3
```

**Comment by wangyi-fudan** [comment]
Thanks for your suggestion, but I have two comments:
1: your modified code is not correct, because even come from loop, 1-3 byte need to be processed.
2: I take your idea, but I find that we need to initialized loop and set it to 1 after the loop, and branch it by _likely_. I think the total cost is similar to an extra _wymix. Let's make the code minimal.

**Comment by gzm55** [comment]
1. yes, 1-3 byte should be mixed
2. another method is `for(; i>64; i-=64,p+=64){`, then the last round mixing occurs at line 67, the tail branch

**Comment by wangyi-fudan** [comment]
done! thank you very much!
