### ISSUE TITLE
make_secret is slow

### ISSUE THREAD

**Issue by changloong** [wangyi-fudan/wyhash#62]
build with clang -O3, 4.5G intel cpu:

```sh
time ./a.out 
secret=7354222319401939409, 10064039272631357873

real	0m22.942s
user	0m22.901s
sys	0m0.019s
```

Is a random 16 byte nonce a valid secret ?

**Comment by easyaspi314** [comment]
It is testing not only if each number is prime, but also if each combination of keys XOR'd together has a popcount of exactly 32, which is *incredibly* specific.

I honestly think there is a much better way to approach this.

* For `wyhash_v6`, the only secret values that are used individually are `secret[0]`, `secret[8]`, and `secret[9]`. Everything else is XOR mixed in the bulk loop.
* The individual elements are primes, but *not* if the mixed elements are primes. Theoretically, you could have the mixed lanes generate some really bad number like `0xFFFFFFFF00000000` .
* The lowest byte in the lookup table really only has 35 possible options, simply because the other 35 would automatically be even.


Plus, the combinations you are asking for (especially for v6) are stupidly unlikely.

Let's generate two 16-bit integers from the lookup table, which, while not documented (:frowning:), represents all 8-bit integers that have a popcount of 4.

There are 4900 possible combinations. Only 474, or 9.7%, are prime.

Out of the 224676 combinations of two 474 primes, the number of XOR combinations with a popcount of 8 are 83252, or 37%

The chances of generating two primes that XOR to a popcount of 8 is 0.34%.

While the chances _are_ better with 64-bit integers due to more combinations, it still isn't very likely to generate.

**Comment by wangyi-fudan** [comment]
Now, secret can be any random generated bytes.

**Comment by changloong** [comment]
is there any document to explain why random secret not support anymore ?

**Comment by wangyi-fudan** [comment]
it is still supported, maybe need some edit.

**Comment by changloong** [comment]
glad to know it still supported.

it is not default because it not safe anymore or the speed is not good ? 

maybe a compare list with SipHash-2-4 ?
