### ISSUE TITLE
wyhash 20190324 broke MomentChi2 for wyhash32low from 0.000751594 to 2.76359

### ISSUE THREAD

**Issue by rurban** [wangyi-fudan/wyhash#8]
See my wyhash-20190324 branch
2.7 is too high for my taste for the lower 32bits

I'd rather mix the seed before, not after
```
-       for(i=0,        seed^=_wyp0;    i+32<=len;      i+=32,  p+=32)  seed=_wymum(seed,
       _wymum(_wyr64(p)^_wyp1,_wyr64(p+8)^_wyp2)+_wymum(_wyr64(p+16)^_wyp3,_wyr64(p+24)^_wyp4));
+       for(i=0;        i+32<=len;      i+=32,  p+=32)  seed=_wymum(seed^_wyp0, _wymum(_wyr64(p)^_wyp1,_wyr64(p+8)^_wyp2)^_wymum(_wyr64(p+16)^_wyp3,_wyr64(p+24)^_wyp4));
+       seed^=_wyp0;
```

**Comment by wangyi-fudan** [comment]
if you run it with step 1 or 2, it is perfect. In statistics, a Chi2 of 3.8 means a p-value of 0.05, and is widely accepted as the rejection threshold. 2.7 is not even marginal, just normal variations. The ^ instead of + is due to a unified approach with short keys (the big swich). the change from + to ^ for the short keys is due to a avalance of 136bit.

Running 1st unseeded MomentChi2 for the low 32bits/step 1 ... 1391273.174688 - 343.628079
Running 2nd   seeded MomentChi2 for the low 32bits/step 1 ... 1391278.850823 - 343.633616
KeySeedMomentChi2:	0.0468795	PASS

Running 1st unseeded MomentChi2 for the low 32bits/step 2 ... 1391284.432057 - 687.255426
Running 2nd   seeded MomentChi2 for the low 32bits/step 2 ... 1391280.514057 - 687.327458
KeySeedMomentChi2:	0.0111675	PASS

**Comment by rurban** [comment]
Ok, so I'll keep it then. Thanks
